### ISSUE TITLE
Sensor Status

### ISSUE THREAD

**Issue by ghost** [Drealine/weatherlinklive-driver-weewx#23]
Following on from my question about the Sensor Status update.

Is it possible to amend something (your driver or something in weewx.conf file or something in skins.conf etc) so that only the Battery Status is displayed and all other sensor stuff is omitted.

My coding skills or limited so if it is possible instructions would need to be simple and detailed! :)

Just to make it look a bit tidier. Many many thanks

<img width="417" alt="Screenshot 2020-12-07 at 11 57 52 am" src="https://user-images.githubusercontent.com/75205650/101348764-1d19ca00-3884-11eb-9ba8-47a80d230e5b.png">

**Comment by Drealine** [comment]
Hi @JansonBHong,

Not possible. The values of sensors that showing is depending to your Weewx archive interval.

If your Weewx archive is set to 15min, the problem will not appear because Weatherlink.com register those values each 15min.
But if you're Weewx archive is another value, each time that the WLLDriver have not this values, a N/A will be show on your website.

On my website : https://meteo-jussy.fr, I use the Belchertown skill with a graphical wich show those values with an average. With this option, I've not a, None value for each.

Regards,

-Drealine

**Comment by ghost** [comment]
Once again many thanks for your help
